version: '3.5'

services:

  stdybdy-img:
    container_name: stdybdy-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4200:4200'
